### ISSUE TITLE
Practica 4 y 5

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-4y5-team-noble#1]
[Practicas 4 y 5.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-team-noble/files/8682248/Practicas.4.y.5.pdf)

**Comment by Nayee123** [comment]
Muy buen trabajo 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
